### ISSUE TITLE
Message d'erreur avec ce module 

### ISSUE THREAD

**Issue by gregtux77** [vincentBesseau/gladys-hdmicec#1]
Bonjour,

Le module fonctionne mais cependant j ai des messages d'erreurs...
dans la log  Error in script : TypeError: Cannot read property 'say' of undefined

il ne peut me récupérer l'etat du device ... 

Une idee?

**Comment by vincentBesseau** [comment]
Salut !
Le problème provenait d'une ligne de code utilisant le module speak.
Si tu mets a jour le module dans Gladys rencontre tu encore le problème ?
