### ISSUE TITLE
Turn On/Off TV too long

### ISSUE THREAD

**Issue by thomasGomes** [vincentBesseau/gladys-hdmicec#4]
Hi,

The functions "tunOffTv" and "tunOnTv" use "sleep 10" which make my script very long to execute.
I have commented these lines in my gladys hooks, but can you modify your code to make my modification persistent (and for the others)?

Thanks

--

https://github.com/vincentBesseau/gladys-hdmicec/blob/9861e5ae2ba312f7db76dee6ec7926a4121c66cf/scripts/functionTv.sh#L57

https://github.com/vincentBesseau/gladys-hdmicec/blob/9861e5ae2ba312f7db76dee6ec7926a4121c66cf/scripts/functionTv.sh#L64

**Comment by vincentBesseau** [comment]
Hi thomas !

My samsung TV takes about 7 seconds to turn off and turn on, that's why I put a 10 second tempo.

I understand your point and I will reflect to set this value in gladys.

Thx

**Comment by vincentBesseau** [comment]
Hi Thomas I make a new optional parameter HDMI_INTERVAL_TEMPO to fix this issue.
You can update this module on gladys.

Thank you for your help
